- openmeetings-server/src/site/resources/css/site.css
- openmeetings-server/src/site/resources/js/site.js
- pom.xml
- src/site/site.xml
Hi @solomax,
I publish a new version of reflow maven plugin and I would like to suggest you this pull request in order to simplify your work.
This version modifies how the header is displayed (See the home page of site https://devacfr.github.io/reflow-maven-skin/) and the `cssClass` attribute of each component do not override anymore `theme` and `background` attribute.
> Bump reflow maven plugin to 2.3.0

- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/WbPanel.html
- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/raw-wb-area.js
- openmeetings-web/src/main/webapp/css/raw-wb.css
Fixes:
* right click menu only over whiteboard name span/text. Instead of entire tab element. Including the close icon
* Update close icon to remove border 
* Fix that right click action is pointing to correct trigger
New layout looks a bit more light:
Tested fix with 2 participants across Chrome + Firefox.
> OPENMEETINGS-2251 Fix JS and CSS for tabbar for right click menu

- openmeetings-web/src/main/webapp/css/raw-wb.css
Fix up CSS. After CSP fix, bootstrap CSS gets loaded now. And that overwrites the border and padding.
> OPENMEETINGS-2247 Fix css that is now loaded from bootstrap

- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/WbPanel.html
- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/raw-wb-area.js
- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/raw-wb-board.js
- openmeetings-web/src/main/webapp/css/raw-wb.css
As described in OPENMEETINGS-2275
Whiteboard panel view without document:
Whiteboard panel view with document:
The toolbar has a min-width, so that it won't page break if you resize the window to smaller then toolbar. Since changing layout from row to column doesn't make sense.
> OPENMEETINGS-2275 Update whiteboard tools bar with proposed design 

- openmeetings-web/src/main/java/org/apache/openmeetings/web/common/tree/FolderPanel.java
- openmeetings-web/src/main/webapp/css/raw-room.css
- openmeetings-web/src/main/webapp/css/raw-tree.css
* Calc width for file tree item that has no error
* Calc width for file tree item that has an error (32px space for error icon)
* Recalc when you resize
* Has a minimum width of 60px on the tree-item text
* For items shorter then the remaining space the warning icon stays attached to the text
* It will work up to 7 sub-levels in the tree, afterwards it applies the width of the 7th level for sub-sequent levels
Maybe you can argue that limiting to 7-levels is not technically perfect. But there are also some limitations without adding too many custom css-classes to mark levels.
> OPENMEETINGS-2344 Resize according to size

- openmeetings-web/src/main/webapp/css/raw-room.css
Looking at the Tab Header they are rather small cut:
image.png
- Blue icon with number of participants overlays User text
- Files icon hardly fits inside
Is there any issue in making this bigger - as long as the tabs have enough space?
This PR changes it to display a bit more spacing around icon and text (if there is space):
But then when it gets too small it still converts it into the mini version (as-is behaviour)
Should be a simple PR I think.
> OPENMEETINGS-2343 Menu header minor change to spacing and size 

- openmeetings-web/src/main/webapp/css/raw-variables.css
Simple fix. But does the job for now:
Would be good to introduce resizing the panel. But maybe that is a future. Especially since the name of the recording can't be edited right now. So you won't exceed width unless you do nested folders.
> OPENMEETINGS-2347 Fix to apply width based on sidebar same as in room.

- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-sharer.js
- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-video-util.js
- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-video.js
- versioning for edge browsers is inconsistent across platforms and is unreliable for differentiation between EdgeHTML and Blink engines
- introduce new VideoUtil.isEdgeChromium and check in both isEdge and isEdgeChromium if EdgeHTML's exclusive MSGestureEvent is available
- this will also fix wrong audio destination issue
> [OPENMEETINGS-2349] new chromium-edge detection method and fixes

- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-video.js
- openmeetings-web/src/main/webapp/css/raw-room.css
This fix moves the icons on top of the drag element.
By doing this you can drag it on mobile touch _and_ yo ucan still click the icons.
This fixes the issue that on mobile/touch devices you can't click on the icons as the DIV with the ui-titlebar is on top.
This is similar to the fix as suggest by @solomax in the Jira.
> OPENMEETINGS-2339 Fix issue around icons hidden behind drag for video pod

- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-sharer.js
- openmeetings-web/src/main/webapp/css/raw-room.css
Thats following the approach of having a separated div in top of the draggable DIV in order to make the close icon clickable on touch surface: Cloning existing one and moving it one layer up.
> OPENMEETINGS-2339 Fix sharer window for touch surface close icon clone.

- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/WbPanel.html
- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/raw-wb-board.js
Actually this dialog didn't work on Mobile/Touch at all: The draggable was applied to the entire DIV. Which meant on mobile: You can't actually click into the text area. 
So basically this dialog was neither possible to close, nor could you do anything with it, cause not possible to enter text.
> OPENMEETINGS-2357 Add handle for draggable and move close icon outside titlebar

- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/WbPanel.html
- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/raw-wb-board.js
Fixes that on mobile/touch surface you can:
- Close the dialog again
- can click inside any of the text boxes or colors pickers or buttons
Still retains draggable.
I did not see any drawbacks.
> OPENMEETINGS-2360 Fix draggable on ui-titlebar and button to close outside of it

- openmeetings-web/src/main/webapp/css/raw-room.css
I accidentally reverted this CSS when merging the fix for the sharer and the video pod buttons.
Now it works as expected.
> OPENMEETINGS-2308 Re-add accidentally merged out of the code CSS from video pod fix

- openmeetings-web/src/main/java/org/apache/openmeetings/web/common/main.js
- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-sharer.js
- openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/raw-wb-area.js
- openmeetings-web/src/main/webapp/css/theme_om/jquery-ui.css
Moving close icon on top.
Although this dialog does not make much sense for Mobile/Touch cause it says "right click and save as" => You can't right click on Mobile devices on anything. 
Anyway, I added another ticket for that, this PR/ticket just fixes so that you can at least close the dialog.
> OPENMEETINGS-2356 Move close icon on top of ui-titlebar so that mobile and touch can click it

- openmeetings-web/pom.xml
- openmeetings-web/src/test/jetty/web.xml
This supplies a dev version for the web.xml that does not filter/security.
Jetty filter restrictions look different from Tomcat, so the effect before this change was that if you try to access WebService when running in Jetty was that you always get a 403.
With this change the filters are removed and everything is public readable.
But: Since jetty is only used in dev mode, I think that is fine.
> OPENMEETINGS-2470 Fix and remove filters while running in dev version.

- openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/BaseWebService.java
- openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/CalendarWebService.java
- openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/FileWebService.java
- openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/GroupWebService.java
- openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RecordingWebService.java
- openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RoomWebService.java
- openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/UserWebService.java
- openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/WbWebService.java
- openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/error/InternalServiceException.java
- openmeetings-webservice/src/test/java/org/apache/openmeetings/webservice/TestBaseService.java
This will improve that the response will contain the actual error.
For Soap Responses it will work fine.
For Json it would be better to not only improve that it returns the actual error but also generates Json in the error response, instead of a HTML error page. So that you can parse the error in Json and actually use.
> OPENMEETINGS-2560 Improve response to return the actual error to client.

- openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/StreamProcessor.java
- openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/StreamProcessorActions.java
- openmeetings-core/src/test/java/org/apache/openmeetings/core/remote/BaseMockedTest.java
- openmeetings-util/pom.xml
- openmeetings-util/src/main/java/org/apache/openmeetings/util/logging/PrometheusAspect.java
- openmeetings-util/src/main/java/org/apache/openmeetings/util/logging/PrometheusUtil.java
- openmeetings-util/src/main/java/org/apache/openmeetings/util/logging/TimedApplication.java
- openmeetings-util/src/main/java/org/apache/openmeetings/util/logging/TimedDatabase.java
- openmeetings-web/pom.xml
- openmeetings-web/src/main/java/org/apache/openmeetings/web/util/logging/OpenMeetingsMetricsServlet.java
- openmeetings-web/src/main/java/org/apache/openmeetings/web/util/logging/TomcatGenericExports.java
- openmeetings-web/src/main/webapp/WEB-INF/classes/applicationContext.xml
- openmeetings-web/src/main/webapp/WEB-INF/web.xml
- pom.xml
As discussed:https://markmail.org/thread/new2mdd6jbyp2o6i
https://issues.apache.org/jira/browse/OPENMEETINGS-2577 Enables metrics - but in disabled state by default.
By default all gathering of metrics as well as exposing metrics is disabled!
In order to enable it there needs to be configuration in the web.xml and applicationContext.xml updated.
See documentation on how to enable it:
https://cwiki.apache.org/confluence/display/OPENMEETINGS/Prometheus+Logging+and+Metrics#PrometheusLoggingandMetrics-EnableMetrics
> OPENMEETINGS-2577 performance  metrics disabled state

- openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/KStream.java
- openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/StreamProcessorActions.java
Just adding logging for now to make missed iceCandidates visible + adding queue as discussed in mailing list according to Kurento examples.
Tbd further via mailing list: https://markmail.org/thread/eadssnmeo255dsll
> OPENMEETINGS-2580 Enable additional logs for making failed attempts to add ice candidate visible

- openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/AbstractStream.java
- openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/KStream.java
- openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/KTestStream.java
- openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/KurentoHandler.java
- openmeetings-core/src/test/java/org/apache/openmeetings/core/remote/BaseMockedTest.java
- openmeetings-web/src/main/webapp/WEB-INF/classes/openmeetings.properties
See Jira at https://issues.apache.org/jira/browse/OPENMEETINGS-2601
This config is required in KMS and also when initialising the WebRtcEndpoint via the constructor. Just doing KMS config, will have no effect.
> OPENMEETINGS-2601 Able to configure which certificate type to use for WebRtcEndpoint

- openmeetings-server/src/site/xdoc/BuildInstructions.xml
Sync website changes back to source XML files.
There would be also a way to just run it via NPM, which is probably even more fast. But I think it is easier to just use the MVN commands, as it mimics exactly the same thing the OpenMeetings build process does.
> OPENMEETINGS-2654 Update website with new commands for updating JS code dynamically

- openmeetings-web/src/main/webapp/css/raw-room.css
Seems to fix the issue to have the text visible and side panel minimise button smaller so it won't overlap with tab bar buttons:
> OPENMEETINGS-2725 Update css for user and minimise button

- openmeetings-web/src/main/webapp/css/raw-room.css
Add some styles to quick poll popup. I think border with white background will look better for the icons:
> OPENMEETINGS-2726 Add some border styles to quick poll fixed popup

- openmeetings-server/src/site/xdoc/BuildInstructions.xml
- openmeetings-web/pom.xml
- pom.xml
Use **-Dwicket.ioc.useByteBuddy=true**
`mvn install -P allModules,quick,mysql jetty:run -Dwicket.configuration=DEVELOPMENT -Dwicket.ioc.useByteBuddy=true`
And include bytebuddy for mysql profile only for now. 
I'm not sure why you would not needed it you run Tomcat. Only for Jetty.
> OPENMEETINGS-2743 Add option to use bytebuddy for Wicket cglib.

- openmeetings-server/src/site/xdoc/BuildInstructions.xml
Update build instructions. I think the Wicket.mode was missing, it fails without it.
Otherwise I think just publishing the changes on the website may have been missing.
> OPENMEETINGS-2748 Add and update build instructions.
