apache/openmeetings

openmeetings-web/src/main/java/org/apache/openmeetings/web/app/Application_ja.properties.xml

Last time when I updated the Japanese lang file is over five years ago, probably.
It seems that nobody has updated it since then, unfortunately...
This time, I had to update my OpenMeetings due to Chrome's new Flash (SSL) restriction, so I updated the JP lang file again.

update Japanese language file.

---

openmeetings-server/src/main/assembly/ROOT/index.html

Primarily an accessibility concern for screen reader software.

Added HTML lang="en"

---

pom.xml

I'm just testing PR plugin
Below was just me struggling finding some quicker way to run the build.

OPENMEETINGS-2230 Feature/add more quick run options

---

README.md

Update Readme with CI links and status

Update Readme with CI links and status

---

openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-sharer.js
openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-video-manager.js
openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-video.js

Reset values when re-entering room.
And fix stoped to stopped. Stoped would be past tense for "stope".

OPENMEETINGS-2338 Fix reset of values in browser when re-entering room

---

openmeetings-web/src/main/webapp/css/raw-tree.css

Add horizontal scrollbar to show in case files still bigger than size.

OPENMEETINGS-2344 Add horizontal scroll if size exceeds window size.

---

openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-room.js
openmeetings-web/src/main/webapp/css/raw-room.css
openmeetings-web/src/main/webapp/css/raw-tree.css
openmeetings-web/src/main/webapp/css/raw-variables.css
openmeetings-web/src/main/webapp/css/raw-wb.css

As per review comments on https://github.com/apache/openmeetings/pull/81

OPENMEETINGS-2347 Fix rename of now common variable.

---

openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/KRoom.java
openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/KStream.java
openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/KurentoHandler.java
openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/StreamProcessor.java
openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/TestStreamProcessor.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/room/RoomPanel.java

- add user uid for TURN username in REST mode
- allow to specify multiple comma-separated STUN/TURN servers including encrypted versions

[OPENMEETINGS-2368] improvements for ICE parameters

---

openmeetings-util/src/main/java/org/apache/openmeetings/util/OMContextListener.java

Minor fix to suppress having shown a NullPointerException on startup.

OPENMEETINGS-2411 Fix Nullpointer on startup.

---

openmeetings-server/src/site/xdoc/BuildInstructions.xml

Needs to copy resulting files also to https://github.com/apache/openmeetings-site once this PR is done.

Update Javascript and Build Instructions.

---

openmeetings-util/src/main/java/org/apache/openmeetings/util/OmFileHelper.java

OPENMEETINGS-2434 Add some logging to better find out what env variable has been picked up.

OPENMEETINGS-2434 Add some logging to better find out what env variable has been picked up.

---

openmeetings-web/src/main/java/org/apache/openmeetings/web/room/RoomPanel.html
openmeetings-web/src/main/java/org/apache/openmeetings/web/room/raw-video-util.js

Additional classes for dialog to be able to uniquely identify the OK button via Selenium/WebDriver

OPENMEETINGS-2504 Add css classes for dialog to make CSS selector possible

---

openmeetings-web/src/test/java/org/apache/openmeetings/webservice/TestRoomService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RoomWebService.java

OPENMEETINGS-2565 Spelling mistake in web service method

---

openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/KStream.java

Only stop in case in case its audio-only room for type AUDIO events.

OPENMEETINGS-2573 filter out audio Type events to not stop video streams

---

openmeetings-web/src/main/java/org/apache/openmeetings/web/common/OmWebSocketPanel.java

Reduce log level for this message.

OPENMEETINGS-2575 Log file fills up with ping messages.

---

openmeetings-core/src/main/java/org/apache/openmeetings/core/remote/KStream.java

As discussed this queued candidates apparently need to be applied before the WS call.
According to the Kurento examples and testing seems to confirm.
This seems to also reduce the number of "onIceCandidate" events.

OPENMEETINGS-2580 re apply ice before sending ws candidates

---

openmeetings-web/src/main/webapp/css/raw-menu.css
openmeetings-web/src/main/webapp/css/raw-room.css

2 minor adjustments, see https://issues.apache.org/jira/browse/OPENMEETINGS-2655 for screenshots.

OPENMEETINGS-2655 Adjust sidebar and desktop sharer icon to fit into button and menu

---

openmeetings-webservice/pom.xml
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/CalendarWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/ErrorWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/FileWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/GroupWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/InfoWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/NetTestWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RecordingWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RoomWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/UserWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/WbWebService.java
pom.xml

Update documentation and add annotation for Tag for grouping Rest Services

OPENMEETINGS-2420 Update documentation and tagging for documenting Rest API. Sync with website

---

openmeetings-webservice/pom.xml
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/CalendarWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/ErrorWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/FileWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/GroupWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/InfoWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/NetTestWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RecordingWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RoomWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/UserWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/WbWebService.java

OPENMEETINGS-2660 Update response codes and objects to be generated. Add UserService API tags for documentation.
+ sync new schema to website

OPENMEETINGS-2660 Update response codes objects and remaining Services

---

openmeetings-webservice/pom.xml
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/CalendarWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/ErrorWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/FileWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/GroupWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/InfoWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/NetTestWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RecordingWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RoomWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/UserWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/WbWebService.java

Re-write tags / description to make them write in a more useful order.

OPENMEETINGS-2660 Update specs generated so that ordering in generated docs is defined.

---

openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/CalendarWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/ErrorWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/FileWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/GroupWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/InfoWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RecordingWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RoomWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/UserWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/WbWebService.java

+ regenerate swagger with updated definitions

OPENMEETINGS-2664 Fix consumes tag so generated swagger is correct.

---

openmeetings-server/src/site/xdoc/ConfluencePlugin.xml
openmeetings-server/src/site/xdoc/JiraPlugin.xml
openmeetings-server/src/site/xdoc/RestAPISample.xml
openmeetings-webservice/pom.xml

OPENMEETINGS-2661 Add Rest examples and add Node.js Module.

---

openmeetings-server/src/site/xdoc/RestAPISample.xml

OPENMEETINGS-2661 Fix link and typo.

---

openmeetings-server/src/site/xdoc/RestAPISample.xml

OPENMEETINGS-2661 Fix another typo.

---

openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/CalendarWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/ErrorWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/FileWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/GroupWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/InfoWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RecordingWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/RoomWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/UserWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/WbWebService.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/AppointmentDTOListWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/AppointmentDTOWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/FileExplorerObjectWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/FileItemDTOListWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/FileItemDTOWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/GroupDTOListWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/HealthWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/InfoWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/RecordingDTOListWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/RoomDTOListWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/RoomDTOWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/ServiceResultWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/UserDTOListWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/UserDTOWrapper.java
openmeetings-webservice/src/main/java/org/apache/openmeetings/webservice/schema/UserSearchResultWrapper.java

See Jira ticket: https://issues.apache.org/jira/browse/OPENMEETINGS-2667
Populates:
- Schema to matches actual response. Including the wrapping root element
- Add example responses 
And also: Sync with schema published on website

OPENMEETINGS-2667 update schema definition for response wrapping in root element and example values

---

openmeetings-server/src/site/xdoc/RestAPISample.xml
openmeetings-server/src/site/xdoc/index.xml

Add PHP example integration and sync website

OPENMEETINGS-2674 Update and add section for PHP Composer client module.

---

openmeetings-server/src/site/markdown/InstallMediaServer.md

Update docu without fixing the outdated banner for apache con from #176

OPENMEETINGS-2728 Fix KMS Media Website docu only.

---

openmeetings-core/pom.xml
openmeetings-mediaserver/pom.xml
openmeetings-mediaserver/src/main/java/org/apache/openmeetings/mediaserver/remote/AbstractStream.java
openmeetings-mediaserver/src/main/java/org/apache/openmeetings/mediaserver/remote/IStreamProcessor.java
openmeetings-mediaserver/src/main/java/org/apache/openmeetings/mediaserver/remote/KRoom.java
openmeetings-mediaserver/src/main/java/org/apache/openmeetings/mediaserver/remote/KStream.java
openmeetings-mediaserver/src/main/java/org/apache/openmeetings/mediaserver/remote/KTestStream.java
openmeetings-mediaserver/src/main/java/org/apache/openmeetings/mediaserver/remote/KurentoHandler.java
openmeetings-mediaserver/src/main/java/org/apache/openmeetings/mediaserver/remote/StreamProcessor.java
openmeetings-mediaserver/src/main/java/org/apache/openmeetings/mediaserver/remote/StreamProcessorActions.java
openmeetings-mediaserver/src/main/java/org/apache/openmeetings/mediaserver/remote/TestStreamProcessor.java
openmeetings-mediaserver/src/test/java/org/apache/openmeetings/mediaserver/remote/BaseMockedTest.java
openmeetings-mediaserver/src/test/java/org/apache/openmeetings/mediaserver/remote/TestNotConnectedMocked.java
openmeetings-mediaserver/src/test/java/org/apache/openmeetings/mediaserver/remote/TestRecordingFlowMocked.java
openmeetings-mediaserver/src/test/java/org/apache/openmeetings/mediaserver/remote/TestRoomFlowMocked.java
openmeetings-mediaserver/src/test/java/org/apache/openmeetings/mediaserver/remote/TestSetupFlowMocked.java
openmeetings-web/pom.xml
openmeetings-web/src/main/java/org/apache/openmeetings/web/admin/connection/ConnectionsPanel.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/admin/connection/KStreamDto.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/app/Application.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/app/ClientManager.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/app/TimerService.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/common/OmWebSocketPanel.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/room/RoomPanel.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/room/menu/RoomMenuPanel.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/room/sidebar/RoomSidebar.java
openmeetings-web/src/main/java/org/apache/openmeetings/web/room/wb/InterviewWbPanel.java
pom.xml

Introduce openmeetings-mediaserver and move *.remote package from openmeetings-core to openmeetings-mediaserver.

OPENMEETINGS-2742 Introduce openmeetings-mediaserver module.
